server:
  servlet:
    context-path: /   #url的前缀
    session:
          timeout: 10  # session超时时间
  port: 8282
  session-timeout: 30 # 无效
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8

spring:
  airesource_server: /home/workspace/deploy/build_airesource_server.sh
  airesource_user: a
  airesource_admin: a
